/*
  resources.h - Resource identifiers for Console.

  Jason Hood, 3 December, 2009.
*/

#define IDS( id ) (rsrcid + IDS_##id)

#define IDS_VERSION		100
#define IDS_GAME_SAVED		101	// false & true
#define IDS_QUICK_SAVE		103
#define IDS_GAME_NOT_FOUND	104
#define IDS_OBJECT_NOT_FOUND	105
#define IDS_CRUISESPD		106
#define IDS_CRUISEACC		107
#define IDS_ANIMATION_NOT_FOUND 108
#define IDS_BASE_NOT_FOUND	109
#define IDS_SYSTEM_NOT_FOUND	110
#define IDS_SHIPS		111
#define IDS_SHIP_NOT_FOUND	112
#define IDS_NO_SHIPS_HERE	113
#define IDS_REPAIR_DAMAGE	114
#define IDS_PARKED		115
#define IDS_DRIVE_A_SHIP	116
#define IDS_SOLD_FOR		117
#define IDS_SPECIFY_BASE	118
#define IDS_GHOST_OFF		119
#define IDS_GHOST_ON		120
#define IDS_GODMODE_OFF 	121
#define IDS_GODMODE_ON		122
#define IDS_NTB_OFF		123
#define IDS_NTB_ON		124	// on & sight
#define IDS_SHOW_ON		126
#define IDS_SHOW_OFF		127
#define IDS_HOUSES_OFF		128
#define IDS_HOUSES_ON		129
#define IDS_PPATHS_UNFILTERED	130
#define IDS_PPATHS_FILTERED	131
#define IDS_ZOOM_TIME		132
#define IDS_FACTION_NOT_FOUND	133
#define IDS_REP 		134
#define IDS_REP_SAVED		135
#define IDS_REP_LOADED		136
#define IDS_MONKEY		137
#define IDS_ROBOT		138
#define IDS_TRENT		139
#define IDS_COSTUME_NOT_FOUND	140
#define IDS_TRANSFER		141	// title & help
#define IDS_NO_CLIP		143
#define IDS_COPIED		144
#define IDS_BOOKMARKS		145
#define IDS_BOOKMARK_SET	146
#define IDS_BOOKMARK_NOT_SET	147
#define IDS_SOUND_NOT_FOUND	148
#define IDS_ROLLED          149
#define IDS_PONG            150
#define IDS_HEADS           151
#define IDS_TAILS           152
#define IDS_FLIPPED         153
#define IDS_CMDS            154
#define IDS_UTF_NOT_FOUND	  155
#define IDS_CARGO_NOT_FOUND	 156
#define IDS_CARGO_SUCCESS	   157
#define IDS_CARGO_FAIL	     158
#define IDS_CARGO_ADD	       159
#define IDS_INVALID_QUANTITY 160
#define IDS_LOADOUT_NOT_FOUND 161
#define IDS_LOADOUT_SHIP_NOT_FOUND 162
#define IDS_LOADOUT_SHIP_FAIL 163
#define IDS_LOADOUT_SHIP_CONJ 164
#define IDS_VOICE_NOT_FOUND 165
#define IDS_VOICE_APPLY_CHANGES 166
#define IDS_COMPLETE_CAMPAIGN 167
#define IDS_VOICE_WARNING 168
